# -*- coding: utf-8 -*-
# Generated by Django 5.1.3 on 2024-11-06 13:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "event_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "email"), (2, "whatsapp"), (3, "sms"), (4, "api")]
                    ),
                ),
                (
                    "message",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "sign_up_otp_email"),
                            (2, "login_otp_email"),
                            (3, "resend_otp_email"),
                            (4, "reset_password_email"),
                            (5, "api_response"),
                        ]
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("api_response", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "event_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "email"), (2, "whatsapp"), (3, "sms"), (4, "api")]
                    ),
                ),
                (
                    "message",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "sign_up_otp_email"),
                            (2, "login_otp_email"),
                            (3, "resend_otp_email"),
                            (4, "reset_password_email"),
                            (5, "api_response"),
                        ]
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("api_response", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification",
                "verbose_name_plural": "historical notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
